SEARCH_BOX = "//input[@id='searchBox']"
INPUT_SEARCHING_BUTTON = "//span[@class='input-group-text']"
ADD_BUTTON = "//button[@class='btn btn-primary']"
FIRST_NAME_LOCATOR = "//div[@id='firstName-wrapper']//input[@id='firstName']"
LAST_NAME_LOCATOR = "//div[@id='lastName-wrapper']//input[@id='lastName']"
EMAIL_LOCATOR = "//div[@id='userEmail-wrapper']//input[@id='userEmail']"
AGE_LOCATOR = "//div[@id='age-wrapper']//input[@id='age']"
SALARY_LOCATOR = "//div[@id='salary-wrapper']//input[@id='salary']"
DEPARTMENT_LOCATOR = "//div[@id='department-wrapper']//input[@id='department']"
SUBMIT_BUTTON_LOCATOR = "//div[contains(@class, 'content')]//button[@id='submit']"
# PREVIOUS_AND_NEXT_BUTTON = "//div[@class='-next']//button[@class='-btn' and text()='Next']"
PREVIOUS_AND_NEXT_BUTTON = "//div[@class='{}']//button[@class='-btn' and text()='{}']"
EDIT_LOCATOR = "//div[@class='action-buttons']//span[@title='Edit']"
DELETE_BUTTON = "//div[@class='action-buttons']//span[@title='Delete']"
ROW_PARENT = ".//ancestor::div[@class='rt-tr-group']"
LOCATOR_SALARY_KIERRA = "//div[@id='salary-wrapper']//input[@id='salary']"
EDIT_SUBMIT_BUTTON = "//div[contains(@class, 'text-right')]//button[@id='submit']"
COUNT_ROW_LIST = "//span[contains(@class, 'select-wrap')]//select"
VALUE_ROW_LIST = "//select//option[@value='{}']"
ROW_LOCATOR = "//select[@aria-label='rows per page']"